### ISSUE TITLE
Fix test issue on Windows with XmlModelGenerator

### ISSUE THREAD

**Issue by bfitzpat** [fabric8io/data-mapper#158]
I had a little time today to figure out why the XmlModelGeneratorTest is failing on Windows and nowhere else...

Turns out it's an issue with the System ID being set to a value that includes back slashes instead of forward slashes.

In generateFromSchema you had this line (org.jboss.mapper.model.xml.XmlModelGenerator.generateFromSchema(XmlModelGenerator.java:54):

```
     is.setSystemId(schemaFile.getAbsolutePath());
```

And when we run XmlModelGeneratorTest.generateFromInstance on Windows, I see this:

```
Running org.jboss.mapper.model.xml.XmlModelGeneratorTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.246 sec <<< FAILURE!
generateFromInstance(org.jboss.mapper.model.xml.XmlModelGeneratorTest)  Time elapsed: 0.246 sec  <<< ERROR!
java.lang.IllegalArgumentException: system ID 'E:\Users\bfitzpat\github\fuseide\transformation\common\target\abc-order.xsd' isn't absolute
        at com.sun.tools.xjc.api.impl.s2j.SchemaCompilerImpl.checkAbsoluteness(SchemaCompilerImpl.java:192)
        at com.sun.tools.xjc.api.impl.s2j.SchemaCompilerImpl.parseSchema(SchemaCompilerImpl.java:156)
        at org.jboss.mapper.model.xml.XmlModelGenerator.generateFromSchema(XmlModelGenerator.java:54)
        at org.jboss.mapper.model.xml.XmlModelGenerator.generateFromInstance(XmlModelGenerator.java:88)
        at org.jboss.mapper.model.xml.XmlModelGeneratorTest.generateFromInstance(XmlModelGeneratorTest.java:33)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
        at org.junit.runners.BlockJUnit4ClassRunner.runNotIgnored(BlockJUnit4ClassRunner.java:79)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:71)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:49)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.net.URISyntaxException: Illegal character in opaque part at index 2: E:\Users\bfitzpat\github\fuseide\transformation\common\target\abc-order.xsd
        at java.net.URI$Parser.fail(URI.java:2829)
        at java.net.URI$Parser.checkChars(URI.java:3002)
        at java.net.URI$Parser.parse(URI.java:3039)
        at java.net.URI.<init>(URI.java:595)
        at com.sun.tools.xjc.api.impl.s2j.SchemaCompilerImpl.checkAbsoluteness(SchemaCompilerImpl.java:190)
        ... 33 more
```

Down at the bottom of the stack trace, the SchemaCompiler is throwing a hissy fit when it sees a Windows-style path ( "E:\Users\bfitzpat\github\fuseide\transformation\common\target\abc-order.xsd" ) show up as the System ID...

So...

I propose a minor tweak to the XmlModelGenerator class instead of the current line...

```
        // to work around windows platform issue
        String id = schemaFile.getAbsolutePath().replace('\\', '/');
        is.setSystemId(id);
```

It's a minor tweak, makes the tests on Windows happy, and should NOT affect anything else so far as I can tell with UNIX-style paths.

**Comment by bfitzpat** [comment]
I created a PR here: https://github.com/fusesource/fuseide/pull/160
