### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: org.apache.camel.component.dozer.LiteralMapper

### ISSUE THREAD

**Issue by rhui** [fabric8io/data-mapper#159]
<version.camel>2.15.1.redhat-620133</version.camel>
Caused by: java.lang.ClassNotFoundException: org.apache.camel.component.dozer.LiteralMapper

Looks like the camel-dozer is missing this org.apache.camel.component.dozer.LiteralMapper, and if I don't do the Web->Origin thing, it will work. 

[         Blueprint Extender: 1] BlueprintContainerImpl         ERROR Unable to start blueprint container for bundle org.jboss.mapper.examples.map-0
org.osgi.service.blueprint.container.ComponentDefinitionException: Error when instantiating bean xml2json of class interface org.apache.camel.Endpoint
	at org.apache.aries.blueprint.container.BeanRecipe.getInstance(BeanRecipe.java:300)
	at org.apache.aries.blueprint.container.BeanRecipe.internalCreate2(BeanRecipe.java:806)
	at org.apache.aries.blueprint.container.BeanRecipe.internalCreate(BeanRecipe.java:787)
	at org.apache.aries.blueprint.di.AbstractRecipe$1.call(AbstractRecipe.java:79)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at org.apache.aries.blueprint.di.AbstractRecipe.create(AbstractRecipe.java:88)
	at org.apache.aries.blueprint.container.BlueprintRepository.createInstances(BlueprintRepository.java:245)
	at org.apache.aries.blueprint.container.BlueprintRepository.createInstance(BlueprintRepository.java:230)
	at org.apache.aries.blueprint.container.BlueprintRepository.create(BlueprintRepository.java:145)
	at org.apache.aries.blueprint.container.BlueprintContainerImpl.getComponentInstance(BlueprintContainerImpl.java:746)
	at org.apache.camel.blueprint.BlueprintContainerRegistry.lookupByNameAndType(BlueprintContainerRegistry.java:54)
	at org.apache.camel.impl.CompositeRegistry.lookupByNameAndType(CompositeRegistry.java:56)
	at org.apache.camel.impl.PropertyPlaceholderDelegateRegistry.lookupByNameAndType(PropertyPlaceholderDelegateRegistry.java:63)
	at org.apache.camel.util.CamelContextHelper.lookup(CamelContextHelper.java:137)
	at org.apache.camel.util.CamelContextHelper.mandatoryLookup(CamelContextHelper.java:157)
	at org.apache.camel.component.ref.RefEndpoint.doStart(RefEndpoint.java:76)
	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
	at org.apache.camel.impl.DefaultCamelContext.startService(DefaultCamelContext.java:2869)
	at org.apache.camel.impl.DefaultCamelContext.doAddService(DefaultCamelContext.java:1097)
	at org.apache.camel.impl.DefaultCamelContext.addService(DefaultCamelContext.java:1058)
	at org.apache.camel.impl.DefaultCamelContext.addService(DefaultCamelContext.java:1054)
	at org.apache.camel.impl.DefaultCamelContext.getEndpoint(DefaultCamelContext.java:574)
	at org.apache.camel.util.CamelContextHelper.getMandatoryEndpoint(CamelContextHelper.java:79)
	at org.apache.camel.model.RouteDefinition.resolveEndpoint(RouteDefinition.java:200)
	at org.apache.camel.impl.DefaultRouteContext.resolveEndpoint(DefaultRouteContext.java:107)
	at org.apache.camel.impl.DefaultRouteContext.resolveEndpoint(DefaultRouteContext.java:113)
	at org.apache.camel.model.SendDefinition.resolveEndpoint(SendDefinition.java:62)
	at org.apache.camel.model.SendDefinition.createProcessor(SendDefinition.java:56)
	at org.apache.camel.model.ProcessorDefinition.makeProcessorImpl(ProcessorDefinition.java:527)
	at org.apache.camel.model.ProcessorDefinition.makeProcessor(ProcessorDefinition.java:488)
	at org.apache.camel.model.ProcessorDefinition.addRoutes(ProcessorDefinition.java:218)
	at org.apache.camel.model.RouteDefinition.addRoutes(RouteDefinition.java:1025)
	at org.apache.camel.model.RouteDefinition.addRoutes(RouteDefinition.java:185)
	at org.apache.camel.impl.DefaultCamelContext.startRoute(DefaultCamelContext.java:841)
	at org.apache.camel.impl.DefaultCamelContext.startRouteDefinitions(DefaultCamelContext.java:2895)
	at org.apache.camel.impl.DefaultCamelContext.doStartCamel(DefaultCamelContext.java:2618)
	at org.apache.camel.impl.DefaultCamelContext.access$000(DefaultCamelContext.java:167)
	at org.apache.camel.impl.DefaultCamelContext$2.call(DefaultCamelContext.java:2467)
	at org.apache.camel.impl.DefaultCamelContext$2.call(DefaultCamelContext.java:2463)
	at org.apache.camel.impl.DefaultCamelContext.doWithDefinedClassLoader(DefaultCamelContext.java:2486)
	at org.apache.camel.impl.DefaultCamelContext.doStart(DefaultCamelContext.java:2463)
	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
	at org.apache.camel.impl.DefaultCamelContext.start(DefaultCamelContext.java:2432)
	at org.apache.camel.blueprint.BlueprintCamelContext.start(BlueprintCamelContext.java:180)
	at org.apache.camel.blueprint.BlueprintCamelContext.maybeStart(BlueprintCamelContext.java:212)
	at org.apache.camel.blueprint.BlueprintCamelContext.serviceChanged(BlueprintCamelContext.java:150)
	at de.kalpatec.pojosr.framework.felix.framework.util.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:872)
	at de.kalpatec.pojosr.framework.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:792)
	at de.kalpatec.pojosr.framework.felix.framework.util.EventDispatcher.fireServiceEvent(EventDispatcher.java:540)
	at de.kalpatec.pojosr.framework.PojoSR$1.serviceChanged(PojoSR.java:66)
	at de.kalpatec.pojosr.framework.felix.framework.ServiceRegistry.registerService(ServiceRegistry.java:116)
	at de.kalpatec.pojosr.framework.PojoSRBundleContext.registerService(PojoSRBundleContext.java:88)
	at de.kalpatec.pojosr.framework.PojoSRBundleContext.registerService(PojoSRBundleContext.java:260)
	at org.apache.camel.blueprint.BlueprintCamelContext.init(BlueprintCamelContext.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.aries.blueprint.utils.ReflectionUtils.invoke(ReflectionUtils.java:297)
	at org.apache.aries.blueprint.container.BeanRecipe.invoke(BeanRecipe.java:958)
	at org.apache.aries.blueprint.container.BeanRecipe.runBeanProcInit(BeanRecipe.java:712)
	at org.apache.aries.blueprint.container.BeanRecipe.internalCreate2(BeanRecipe.java:824)
	at org.apache.aries.blueprint.container.BeanRecipe.internalCreate(BeanRecipe.java:787)
	at org.apache.aries.blueprint.di.AbstractRecipe$1.call(AbstractRecipe.java:79)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at org.apache.aries.blueprint.di.AbstractRecipe.create(AbstractRecipe.java:88)
	at org.apache.aries.blueprint.container.BlueprintRepository.createInstances(BlueprintRepository.java:245)
	at org.apache.aries.blueprint.container.BlueprintRepository.createAll(BlueprintRepository.java:183)
	at org.apache.aries.blueprint.container.BlueprintContainerImpl.instantiateEagerComponents(BlueprintContainerImpl.java:668)
	at org.apache.aries.blueprint.container.BlueprintContainerImpl.doRun(BlueprintContainerImpl.java:370)
	at org.apache.aries.blueprint.container.BlueprintContainerImpl.run(BlueprintContainerImpl.java:261)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at org.apache.aries.blueprint.container.ExecutorServiceWrapper.run(ExecutorServiceWrapper.java:106)
	at org.apache.aries.blueprint.utils.threading.impl.DiscardableRunnable.run(DiscardableRunnable.java:48)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.camel.ResolveEndpointFailedException: Failed to resolve endpoint: dozer://xml2json?mappingFile=transformation.xml&marshalId=transform-json&sourceModel=abcorder.ABCOrder&targetModel=xyzorder.XyzOrder&unmarshalId=abcorder due to: java.lang.ClassNotFoundException: org.apache.camel.component.dozer.LiteralMapper
	at org.apache.camel.impl.DefaultCamelContext.getEndpoint(DefaultCamelContext.java:578)
	at org.apache.camel.core.xml.AbstractCamelEndpointFactoryBean.getObject(AbstractCamelEndpointFactoryBean.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.aries.blueprint.utils.ReflectionUtils.invoke(ReflectionUtils.java:297)
	at org.apache.aries.blueprint.container.BeanRecipe.invoke(BeanRecipe.java:958)
	at org.apache.aries.blueprint.container.BeanRecipe.getInstance(BeanRecipe.java:298)
	... 81 more
Caused by: org.dozer.MappingException: java.lang.ClassNotFoundException: org.apache.camel.component.dozer.LiteralMapper
	at org.dozer.util.MappingUtils.throwMappingException(MappingUtils.java:82)
	at org.dozer.util.DefaultClassLoader.loadClass(DefaultClassLoader.java:43)
	at org.dozer.util.MappingUtils.loadClass(MappingUtils.java:224)
	at org.dozer.loader.DozerBuilder$MappingBuilder.classA(DozerBuilder.java:129)
	at org.dozer.loader.xml.XMLParser.parseMapping(XMLParser.java:190)
	at org.dozer.loader.xml.XMLParser.read(XMLParser.java:137)
	at org.dozer.loader.xml.XMLParser.read(XMLParser.java:43)
	at org.dozer.loader.xml.MappingStreamReader.read(MappingStreamReader.java:51)
	at org.dozer.DozerBeanMapper.addMapping(DozerBeanMapper.java:247)
	at org.apache.camel.component.dozer.DozerEndpoint.createDozerBeanMapper(DozerEndpoint.java:130)
	at org.apache.camel.component.dozer.DozerEndpoint.doStart(DozerEndpoint.java:111)
	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
	at org.apache.camel.impl.DefaultCamelContext.startService(DefaultCamelContext.java:2869)
	at org.apache.camel.impl.DefaultCamelContext.doAddService(DefaultCamelContext.java:1097)
	at org.apache.camel.impl.DefaultCamelContext.addService(DefaultCamelContext.java:1058)
	at org.apache.camel.impl.DefaultCamelContext.addService(DefaultCamelContext.java:1054)
	at org.apache.camel.impl.DefaultCamelContext.getEndpoint(DefaultCamelContext.java:574)
	... 89 more
Caused by: java.lang.ClassNotFoundException: org.apache.camel.component.dozer.LiteralMapper
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:274)
	at org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:828)
	at org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:862)
	at org.dozer.util.DefaultClassLoader.loadClass(DefaultClassLoader.java:41)
	... 104 more

**Comment by rhui** [comment]
https://issues.jboss.org/browse/ENTESB-3489

**Comment by rhui** [comment]
Very strange: 
Using map-0 my transformation.xml generated using m3 
    <mapping>
        <class-a>org.apache.camel.component.dozer.LiteralMapper</class-a>
        <class-b>xyzorder.XyzOrder</class-b>
        <field custom-converter-id="_literalMapping" custom-converter-param="Web">
            <a>literal</a>
            <b>origin</b>
        </field>
    </mapping>

but in map-3 
    <configuration>
        <variables>
            <variable name="ORIGIN">Web</variable>
        </variables>
    </configuration>
    <mapping>
        <class-a>org.apache.camel.component.dozer.VariableMapper</class-a>
        <class-b>xyzorder.XyzOrder</class-b>
        <field custom-converter-id="_variableMapping" custom-converter-param="${ORIGIN}">
            <a>literal</a>
            <b>origin</b>
        </field>
    </mapping>

Questions: 
1. Should we use map-0 way map-3 way for literal? 
2. If map-0 way for literal then camel dozer is missing the literalmapper.java class. 
3. If map-3 way (using variableMapper), then there is another problem with the datamapper 
3.1 The Literal UI needs to generate the right transform XML
3.2 Also, when I use m3 datamapper, the plugin won't open the transform.xml properly.

**Comment by rhui** [comment]
I found couple other issues related to this: 
1. when you do a mvn clean, and reopen the transform.xml, you will see Unexpected error: java.lang.ClassNotFoundException: abcorder.ABCOrder
b/c it is looking for the class under target. a work around is to mvn install and fail the test but it will populate target generated classes. 

2. Like I mentioned in previous comment 3.2 I open transform.xml with Unexpected error: null
java.lang.NullPointerException
Once I uncommented this [1], it will open in the data mapper editor properly. 

[1]
    <configuration>
        <variables>
            <variable name="ORIGIN">Web</variable>
        </variables>
    </configuration>
    <mapping>
        <class-a>org.apache.camel.component.dozer.VariableMapper</class-a>
        <class-b>xyzorder.XyzOrder</class-b>
        <field custom-converter-id="_variableMapping" custom-converter-param="${ORIGIN}">
            <a>literal</a>
            <b>origin</b>
        </field>
    </mapping>

**Comment by kcbabo** [comment]
You'll want to use the examples and tooling in the fuseide repository as we moved the mapper tooling there several months ago.  I provided links and more info as a comment in ENTESB-3489.

regards,
keith
